title: "OncoHarmony 协作组技术沙龙"
description: "开源技术、开放科学"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# GitHub Pages settings
github:
  repository_url: https://github.com/OncoHarmony-Network/Tech-Workshop

# Default layout for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
